### ISSUE TITLE
confusion about the definition of recurrent net

### ISSUE THREAD

**Issue by xfx0324** [aks2203/easy-to-hard#4]
sorry for a silly question,  but I'm confused, because the definition of RNN I learnt (e.g. from pytorch tutorial https://pytorch.org/tutorials/intermediate/char_rnn_classification_tutorial.html ), every time the forward function return an output and a hidden state(which is passed the next time forward is called), or hidden structure is stored
but in [recurrent_net.py](https://github.com/aks2203/easy-to-hard/blob/main/chess/models/recurrent_net.py) i dont see such a structure(hidden state passed to forward func),  what am I missing here?

**Comment by aks2203** [comment]
Hi there, thanks for reaching out. A classical RNN does typically have an input and a hidden state at each recurrence. Our models deviate slightly from this regime. Instead, it is as if we are only passing the hidden state, or feature maps, at each iteration. The input is non-sequential, and thus can be given to the model only once at the very beginning of the forward pass. Another way to think about this is like depth-wise weight sharing in a standard feed forward model (not designed for sequence inputs).

Does that help? Perhaps consulting the [paper](https://arxiv.org/pdf/2106.04537.pdf) would offer more clarity. In fact, there is a longer discussion of the vary same model architecture in [another paper](https://arxiv.org/pdf/2102.11011.pdf).

**Comment by xfx0324** [comment]
thanks! I'll read those papers
